### ISSUE TITLE
Data and group

### ISSUE THREAD

**Issue by jburel** [mstritt/image-provider-omero#2]
I have a user in 2 groups lab1 and lab2
The tree displays:
 *  under lab1 all the datasets of lab1+lab2
 *  under lab2 all the datasets of lab1+lab2

This is not correct and will lead to some permissions issues

**Comment by mstritt** [comment]
thanks a lot for that hint, I'll fix that for the next release

**Comment by mstritt** [comment]
resolved. Will be in 1.5.5 release.
(remark: this only occurred on datasets not attached to a project)

**Comment by jburel** [comment]
great thanks

**Comment by mstritt** [comment]
included in new Orbit Image Analysis release 3.02
