### ISSUE TITLE
User Group

### ISSUE THREAD

**Issue by jburel** [mstritt/image-provider-omero#3]
The ``user`` group is always displayed (any user is a member of this group). 
and it displays wrongly all the data of the user regardless of the groups see https://github.com/mstritt/image-provider-omero/issues/2

It is possible to have data in the user group but at the moment it is unlikely

**Comment by jburel** [comment]
The ``user`` group should probably not be included in the OMERO gateway browse.getAvailableGroups().

**Comment by mstritt** [comment]
ok, this will be fixed together with #2

**Comment by mstritt** [comment]
done, will be in 1.5.5

**Comment by mstritt** [comment]
included in new Orbit Image Analysis release 3.02
