### ISSUE TITLE
Save Segmented Objects to OMERO as Polygons

### ISSUE THREAD

**Issue by will-moore** [mstritt/image-provider-omero#5]
It would be really nice if you could save the results from Object Segmentation to OMERO as Polygon shapes (one shape per ROI). This would allow Orbit to become part of the image analysis workflow in OMERO.

Perhaps this is a bigger issue than simply image-provider-omero since the Orbit UI will need updating too etc.

**Comment by jburel** [comment]
@mstritt what is the orbit format of those rois/shapes? if you have example we could check how we can convert them

**Comment by mstritt** [comment]
you're right, this would be very useful.
Let's have a short brainstorming here:

- Orbit saves all segmentations / manual drawn annotations / ROIs /... as RawAnnotations
- RawAnnotations simply contain a byte array, but in case of segmentations it's a serialized Ploygon shape.
- the reason why I don't write Omero Polygons is because it's generic and in principal could be anything

Solutions / Workarounds:
- [this script](https://github.com/mstritt/orbit-image-analysis/blob/master/src/main/groovy/com/actelion/research/orbit/imageAnalysis/scripts/AnnotationReader.groovy) shows how to read Orbit annotations and transform them into Shapes (e.g. Polygons).
So this would allow us to process the shapes, e.g. store them as Omero polygons AFTERWARDS.

- we could modify the omero-image-provider that in case the RawAnnotation is a Shape it stores it as an Omero Shape IN ADDITION. This would imply that Shapes modified by Omero would be ignored by Orbit.

- In case of scripting (e.g. [deep learning segmentation](https://github.com/mstritt/orbit-image-analysis/blob/master/src/main/groovy/com/actelion/research/orbit/imageAnalysis/scripts/deepLearning/DeepLearningSegmentation.groovy)), we retrieve a list of shapes and can do anything we want...

anything useful of it?

**Comment by will-moore** [comment]
I don't see a way to save segmentation results in the Orbit UI (reading the Analysis Handbook). Is there a way to convert them to "RawAnnotations" file?

**Comment by mstritt** [comment]
no, saving works only via script, see the [segmentation example](https://github.com/mstritt/orbit-image-analysis/blob/master/src/main/groovy/com/actelion/research/orbit/imageAnalysis/scripts/SegmentationSimple.groovy).

This returns a list of shapes.
Optionally the shapes can be stored as a RawAnnotation ([see here](https://github.com/mstritt/orbit-image-analysis/blob/master/src/main/groovy/com/actelion/research/orbit/imageAnalysis/scripts/AnnotationWriter.groovy)), or somewhere else, e.g. in Omero.

**Comment by mstritt** [comment]
The idea is that via UI the users run only short-running tasks, for longer tasks, e.g. deep learning segmentation, the GroovyExecutor[1] can be used to execute a script in headless mode on server-side. Then the results can be saved and retrieved later.

[1]: via com.actelion.research.orbit.imageAnalysis.tasks.GroovyExecutor <URL>
see [here ](http://www.orbit.bio/groovy-scripts/)for details.

**Comment by jburel** [comment]
* Looking that the scripts it should not be difficult to convert the shapes into OMERO shapes

Thanks for info about headless mode, we will look into that

**Comment by will-moore** [comment]
I've been trying to run the segmentation example script but this takes too long with a Big image (49k x 65k) so I'd like to either:

1. Load the image in the UI, draw an ROI to restrict the segmentation to a smaller area) and then run the script load the model, do the segmentation within the ROI (and save Polygons back to OMERO)
1. OR, run the segmentation in the UI, then use the script to save results. But how do I get hold of the ```SegmentationResult res``` in the script if I've run the segmentation in the UI?
1. OR, create and save an ROI on the image (in OMERO or Orbit), then run the segmentation script and restrict the segmentation to the ROI. For this I'd need to load a Polygon from the image in OMERO?
1. Alternatively I tried cropping the Image in OMERO to create a smaller image to analyse, but it seems that Orbit is using BioFormats to read the image files instead of reading pixel data from OMERO so this approach isn't going to work at the moment.

For 1, I tried using the current image with an ROI drawn on it with
```
ImageFrame iFrame = OIA.getIFrame();
RawDataFile rdf = iFrame.rdf;
```
in the segmentation script, but I see this in the Log
```
11:39:44.205 ERROR - cannot load raw annotations
java.io.EOFException: null
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2626)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1321)
```
I'm not sure what it's trying to load here?

Apologies for the confusion. Thanks.

**Comment by mstritt** [comment]
Approach 1 is the way to go (and 3 would work as well).
You did it right, but unfortunately there is a bug when Orbit tries to store annotations into Omero introduced by 8d1e2e9ed277faf14d1db1da63574af25d3d2d6d (ByteArrayInputStream was never filled).
I'll fix that.
Thanks a lot for that finding!

**Comment by jburel** [comment]
my bad I can see the problem
@mstritt do you want me to push a fix?

**Comment by mstritt** [comment]
@jburel no worries - this is on my side not having tested it probably. I'll push a fix and release a new Orbit version later...

**Comment by mstritt** [comment]
released in image-provider-omero 1.5.7.1/2 and orbit-image-analysis 3.0.3

**Comment by will-moore** [comment]
Hi - thanks for the fix.
However, I'm not sure what was broken before or how it answers my question for 1) above "I'm not sure what it's trying to load here?"

My workflow:
 - Open an image from OMERO
 - Draw a ROI in the UI (I want to restrict the segmentation to this region)
 - Run the script below...
 - Now I'm waiting a very long time because I think Orbit is trying to analyse the whole image. I didn't do anything to try and save or load the ROI that I drew. Previously you said "saving works only via script". So how do I use the ROI that I drew to restrict the segmentation to this region?

<details>
    <summary>This script (expand to show)</summary>

```
import com.actelion.research.orbit.beans.RawDataFile
import com.actelion.research.orbit.imageAnalysis.dal.DALConfig
import com.actelion.research.orbit.imageAnalysis.models.OrbitModel
import com.actelion.research.orbit.imageAnalysis.models.SegmentationResult
import com.actelion.research.orbit.imageAnalysis.utils.OrbitHelper

import java.awt.Shape

/**
 * Simple segmentation. Load image, apply model (local, single threaded).
 * Replace image id and model id.
 *
 * Simple segmentation using the OrbitHelper.Segmentation method.
 *
 */

import com.actelion.research.orbit.imageAnalysis.components.*
import com.actelion.research.orbit.imageAnalysis.models.*
final OrbitImageAnalysis OIA = OrbitImageAnalysis.getInstance();
ImageFrame iFrame = OIA.getIFrame();
println("selected image: "+iFrame);
RawDataFile rdf = iFrame.rdf;

// Load Image from OMERO by Image ID:
// RawDataFile rdf = DALConfig.imageProvider.LoadRawDataFile(76900)
// println("Loaded Image: " + rdf.getFileName())

OrbitModel model = OrbitModel.LoadFromFile("/Users/wmoore/orbit-77928-blackCells.omo")
println("Loaded Model")

// classify the image
SegmentationResult res = OrbitHelper.Segmentation(rdf.rawDataFileId,model, null, 1)

println("SegmentationResult")

// and output the segmented objects (can be cast to polygons)
for (Shape shape: res.shapeList) {
    println(shape)
}

println("Closing")

DALConfig.getImageProvider().close();  // only close if not executed within Orbit
```
</details>

**Comment by mstritt** [comment]
you have to differentiate between temporary ROIs and permanent ROIs (stored in the DB).
A temporary ROI (button in the ribbon bar) will only be used in the UI.
A permanent ROI is defined via the annotation panel (right side). Here you have to draw an annotation, then mark the annotation in the list, click on edit (pencil tool in annotation panel) and set the type to "ROI".
These permanent ROIs are then automatically loaded when analyzing an image. You don't have to load anything manual, your script should work.

Does this work?

**Comment by will-moore** [comment]
Yes, great. Thank you.
I'm now getting a load of Polygons printed:
```
com.actelion.research.orbit.imageAnalysis.models.PolygonExt@c7d57480
com.actelion.research.orbit.imageAnalysis.models.PolygonExt@c3dab5c0
com.actelion.research.orbit.imageAnalysis.models.PolygonExt@bfb13540
```
So we'll look at saving those Polygons to OMERO.
And I can see the Annotation "ROI" saved to OMERO as a file annotation on the Image.
Thanks!

**Comment by mstritt** [comment]
thanks for your time and efforts in that!

**Comment by will-moore** [comment]
Hi - So I got this code working and saving back to OMERO.
A couple of queries:
 - Is there any way for me to get hold of an existing connection to OMERO, instead of having to login again?
 - The Polygons created by the script and saved to OMERO appear to be "Cytoplasma Segmentation" whereas those created when I do segmentation in the Orbit UI are not (see screenshot). I can't see where to disable the "Cytoplasma Segmentation". Is this a setting on the OrbitModel?

<details>
  <summary>segmentaion.groovy</summary>

```
import com.actelion.research.orbit.beans.RawDataFile
import com.actelion.research.orbit.imageAnalysis.dal.DALConfig
import com.actelion.research.orbit.imageAnalysis.models.OrbitModel
import com.actelion.research.orbit.imageAnalysis.models.SegmentationResult
import com.actelion.research.orbit.imageAnalysis.utils.OrbitHelper

import java.awt.Shape

import com.actelion.research.orbit.imageAnalysis.components.*
import com.actelion.research.orbit.imageAnalysis.models.*
import com.actelion.research.orbit.imageprovider.ImageProviderOmero

import omero.gateway.model.*
import omero.model.*
import omero.model.enums.UnitsLength
import static omero.rtypes.rstring;
import static omero.rtypes.rint;
import omero.gateway.facility.BrowseFacility

final OrbitImageAnalysis OIA = OrbitImageAnalysis.getInstance();
ImageFrame iFrame = OIA.getIFrame();
println("selected image: "+iFrame);
RawDataFile rdf = iFrame.rdf;


long omeroImageId = rdf.getRawDataFileId()

println("ID:" + omeroImageId)

ImageProviderOmero imageProvider = new ImageProviderOmero()

imageProvider.authenticateUser("username","password");


OrbitModel model = OrbitModel.LoadFromFile("/Users/wmoore/orbit-77928-blackCells.omo")
println("Loaded Model")

// classify the image
SegmentationResult res = OrbitHelper.Segmentation(rdf.rawDataFileId, model, null, 1)

println("SegmentationResult")

// and output the segmented objects (can be cast to polygons)
for (Shape shape: res.shapeList) {
    String points = shape.listPoints().replace(";", ",")

    p = new PolygonI()
    p.setPoints(rstring(points))
    p.setTheT(rint(0))
    p.setTheZ(rint(0))
    p.setStrokeColor(rint(-65281))   // yellow
    p.setStrokeWidth(new LengthI(2, UnitsLength.PIXEL))

    ImageI image = new ImageI(omeroImageId, false)
    RoiI roi = new RoiI()
    roi.setImage(image)
    roi.addShape(p)

    imageProvider.getGatewayAndCtx().getGateway().getUpdateService(imageProvider.getGatewayAndCtx().getCtx()).saveAndReturnObject(roi)
}

println("Close")
imageProvider.close()
```
</details>


![screen shot 2018-06-15 at 13 12 44](https://user-images.githubusercontent.com/900055/41467908-0ef0b67c-70a0-11e8-9042-2780d5a21705.png)

**Comment by mstritt** [comment]
this was related due to the specific model
