### ISSUE TITLE
Connection using websocket

### ISSUE THREAD

**Issue by jburel** [mstritt/image-provider-omero#7]
OMERO supports websocket since 5.5.
It is currently not possible to use websocket in orbit e.g. using host like ```wss://workshop.openmicroscopy.org/omero-ws``` does not work

This is due to the extra check 
```
    public static boolean connectionOk(String host, int port) {
        boolean connectionOk = false;
        try {
            SocketChannel socketChannel = SocketChannel.open();
            socketChannel.configureBlocking(true);
            connectionOk = socketChannel.connect(new InetSocketAddress(host, port));
            socketChannel.close();
        } catch (Exception e) {
            connectionOk = false;
        }
        return connectionOk;
    }
```
Why do you do that check before attempting a connection to OMERO @mstritt?

Using websocket is important when attempting to connect from location like mybinder.org

see https://github.com/ome/omero-guide-orbit/pull/1 for background
 

cc @dominikl

**Comment by mstritt** [comment]
Hi @jburel ,

thanks a lot for your analysis - I'm happy to fix it ;-).
The reason for this is to check wether there is an OMERO server at the specified hostname/port.
What would be the correct way to check wether the config is correct and an OMERO server is accessible?

Regards,
Manuel

**Comment by jburel** [comment]
In ``authenticateUser``, different errors are thrown for invalid user credentials and invalid hostname. So logic like
```
if (!GraphicsEnvironment.isHeadless()) {
                if (JOptionPane.showConfirmDialog(null,
                        "Do you want to configure an Omero image server connection?\n\n" +
                                "(If you want to reconfigure the Omero connection at a later point of time,\nsimply delete the OrbitOmero.properties file in your user home and program execution folder.)",
                        "Configure Omero Server?", JOptionPane.YES_NO_OPTION)
                        == JOptionPane.YES_OPTION) {
                    OmeroConfigDialog omeroConfigDialog = null;
                    try {
                        if (propsFilename==null) {
                            propsFilename = new File(userHome + File.separator + configFile).getAbsolutePath();
                        }
                        omeroConfigDialog = new OmeroConfigDialog(null, true, propsFilename);
                        RawUtilsCommon.centerComponent(omeroConfigDialog);
                        omeroConfigDialog.setVisible(true);
                        host = omeroConfigDialog.getHost();
                        port = omeroConfigDialog.getPort();
                        webport = omeroConfigDialog.getWebPort();
                        useSSL = omeroConfigDialog.isUseSSL();
                        searchLimit = omeroConfigDialog.getSearchLimit();
                        omeroUserScaleout = omeroConfigDialog.getScaleoutUser();
                    } catch (Exception e) {
                        e.printStackTrace();
                    } finally {
                        if (omeroConfigDialog !=null)
                             omeroConfigDialog.dispose();
                    }
                }
            }
```
could be handled at that level  if the host is incorrect, instead of handling it in the default constructor.
That will mean that ``connectionOk`` will not be necessary.
but that also means that the logic in ``DALConfig.java`` might have to be reviewed.

We are also working on improving the way invalid protocols are handled see 
https://github.com/ome/omero-gateway-java/pull/34

**Comment by jburel** [comment]
Second though: probably the less costly and intrusive change will be to review the implementation of ``connectionOk`` and not use Socker (tcp)
but only check if the host is valid 
The protocol part will need to be stripped out.
e.g. ```InetAddress.getByName("wss://workshop.openmicroscopy.org")```
Then the rest of the code will allow to connect with websocket

**Comment by mstritt** [comment]
resolved with last [commit](https://github.com/mstritt/image-provider-omero/commit/38ff501e53d971b0a1d3e2df336e2a462ef57145) .
If OrbitOmero.properties contains the new option "useWebSockets=true" the method connectionOK will return true without checking the host/port.
Currently this is a workaround, a proper check should be done here.
